sonar.projectKey=GlamStudio
sonar.host.url=http://localhost:9000
sonar.token=squ_0db1299abef91da95d89a3a540069bfee3f5b2ee
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx
sonar.exclusions=**/node_modules/**,**/coverage/**,src/main.jsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
