sonar.projectKey=WebAPIWeb
sonar.working.directory=C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb
sonar.pullrequest.cache.basepath=C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb

242E61B6-7937-49B3-BA31-0739C123BB15.sonar.projectKey=WebAPIWeb:242E61B6-7937-49B3-BA31-0739C123BB15
242E61B6-7937-49B3-BA31-0739C123BB15.sonar.projectName=WebAPIWeb
242E61B6-7937-49B3-BA31-0739C123BB15.sonar.projectBaseDir=C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb
242E61B6-7937-49B3-BA31-0739C123BB15.sonar.sourceEncoding=utf-8
242E61B6-7937-49B3-BA31-0739C123BB15.sonar.tests=
242E61B6-7937-49B3-BA31-0739C123BB15.sonar.sources=\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\Controllers\\AuthController.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\Controllers\\CitasController.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\Controllers\\EncargadosController.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\Controllers\\ServiciosController.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\Controllers\\WeatherForecastController.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\Migrations\\20260606232654_InicialFinal.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\Migrations\\20260606232654_InicialFinal.Designer.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\Migrations\\20260609015941_AgregarCamposUsuario.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\Migrations\\20260609015941_AgregarCamposUsuario.Designer.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\Migrations\\ContextBDModelSnapshot.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\Models\\Cita.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\Models\\ContextBD.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\Models\\Servicio.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\Models\\Usuario.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\Models\\UsuarioLogin.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\Program.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\Services\\JwtServices.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\WeatherForecast.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\obj\\Debug\\net8.0\\WebAPIWeb.GlobalUsings.g.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\obj\\Debug\\net8.0\\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\obj\\Debug\\net8.0\\WebAPIWeb.AssemblyInfo.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\obj\\Debug\\net8.0\\WebAPIWeb.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\appsettings.Development.json",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\appsettings.json",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\global.json",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\WebAPIWeb.http",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\Properties\\launchSettings.json",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\obj\\project.assets.json",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\obj\\WebAPIWeb.csproj.nuget.dgspec.json",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\bin\\Debug\\net8.0\\appsettings.json",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\bin\\Debug\\net8.0\\global.json",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\bin\\Debug\\net8.0\\WebAPIWeb.deps.json",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\bin\\Debug\\net8.0\\WebAPIWeb.runtimeconfig.json",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\bin\\Debug\\net8.0\\WebAPIWeb.staticwebassets.endpoints.json",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\obj\\Debug\\net8.0\\rjsmcshtml.dswa.cache.json",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\obj\\Debug\\net8.0\\rjsmrazor.dswa.cache.json",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\obj\\Debug\\net8.0\\rpswa.dswa.cache.json",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\obj\\Debug\\net8.0\\staticwebassets.build.endpoints.json",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\obj\\Debug\\net8.0\\staticwebassets.build.json",\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\obj\\Debug\\net8.0\\WebAPIWeb.sourcelink.json"

242E61B6-7937-49B3-BA31-0739C123BB15.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\.sonarqube\\out\\0"
242E61B6-7937-49B3-BA31-0739C123BB15.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\.sonarqube\\out\\0\\Issues.json"
242E61B6-7937-49B3-BA31-0739C123BB15.sonar.cs.scanner.telemetry=\
"C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\.sonarqube\\out\\0\\Telemetry.json"

242E61B6-7937-49B3-BA31-0739C123BB15.sonar.working.directory=C:\\Users\\Dell Vostro\\Downloads\\GlamStudio-main (1)\\GlamStudio-main\\WebAPIWeb\\WebAPIWeb\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=242E61B6-7937-49B3-BA31-0739C123BB15

